#!/usr/bin/env php
<?php

use Majkel\Fragment\Codegen;
use Majkel\Fragment\Lexer;
use Majkel\Fragment\Parser;

include __DIR__.'/vendor/autoload.php';

$l = new Lexer(file_get_contents($argv[1]));
$p = new Parser($l->lex());
$g = new Codegen($p->parse());
echo $g->generate();
