#!/usr/bin/env php
<?php

use Majkel\Funktor\Lexer;
use Majkel\Funktor\Parser;

include __DIR__.'/vendor/autoload.php';

$l = new Lexer(file_get_contents($argv[1]));
$p = new Parser($l->lex());
print_r($p->parse());
